---
name: Automerge

# yamllint disable-line rule:truthy
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'CI'

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
